language: julia

julia:
 - 0.4
 - nightly

sudo:
 false

install:
  # DataStructures is for the benchmarking script
  - julia -e 'Pkg.init();Pkg.add("DataStructures")'
  - julia -e 'Pkg.clone(pwd());'

script:
  - julia test/runtests.jl
  - julia misc/cms.jl
